// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy_web_key_replace_with_actual',
    appId: '1:000000000000:web:dummyid',
    messagingSenderId: '000000000000',
    projectId: 'jenisha-app',
    authDomain: 'jenisha-app.firebaseapp.com',
    storageBucket: 'jenisha-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72UmM3pMwRBh0pKjKy_jN9wmpE_MP_GM',
    appId: '1:245020879102:android:05969fe2820677483c9daf',
    messagingSenderId: '245020879102',
    projectId: 'jenisha-46c62',
    storageBucket: 'jenisha-46c62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy_ios_key_replace_with_actual',
    appId: '1:000000000000:ios:dummyid',
    messagingSenderId: '000000000000',
    projectId: 'jenisha-app',
    storageBucket: 'jenisha-app.appspot.com',
    iosBundleId: 'com.example.jenishaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy_macos_key_replace_with_actual',
    appId: '1:000000000000:macos:dummyid',
    messagingSenderId: '000000000000',
    projectId: 'jenisha-app',
    storageBucket: 'jenisha-app.appspot.com',
    iosBundleId: 'com.example.jenishaFlutter',
  );
}
